# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/UWOpticalSystemDesigner/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1255, 693)
        MainWindow.setMinimumSize(QtCore.QSize(1, 0))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.modesStack = QtWidgets.QStackedWidget(self.centralWidget)
        self.modesStack.setObjectName("modesStack")
        self.designerpage = QtWidgets.QWidget()
        self.designerpage.setObjectName("designerpage")
        self.OutputBox = QtWidgets.QGroupBox(self.designerpage)
        self.OutputBox.setGeometry(QtCore.QRect(0, 460, 1237, 139))
        self.OutputBox.setObjectName("OutputBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.OutputBox)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.exposureUnitsLabel = QtWidgets.QLabel(self.OutputBox)
        self.exposureUnitsLabel.setObjectName("exposureUnitsLabel")
        self.gridLayout_4.addWidget(self.exposureUnitsLabel, 3, 2, 1, 1)
        self.apertureUnitsLabel = QtWidgets.QLabel(self.OutputBox)
        self.apertureUnitsLabel.setObjectName("apertureUnitsLabel")
        self.gridLayout_4.addWidget(self.apertureUnitsLabel, 2, 2, 1, 1)
        self.fovyValueLabel = QtWidgets.QLabel(self.OutputBox)
        self.fovyValueLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.fovyValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fovyValueLabel.setObjectName("fovyValueLabel")
        self.gridLayout_4.addWidget(self.fovyValueLabel, 1, 1, 1, 1)
        self.fovyDegValueLabel = QtWidgets.QLabel(self.OutputBox)
        self.fovyDegValueLabel.setObjectName("fovyDegValueLabel")
        self.gridLayout_4.addWidget(self.fovyDegValueLabel, 1, 3, 1, 1)
        self.avgImgValueValueLabel = QtWidgets.QLabel(self.OutputBox)
        self.avgImgValueValueLabel.setObjectName("avgImgValueValueLabel")
        self.gridLayout_4.addWidget(self.avgImgValueValueLabel, 1, 7, 1, 1)
        self.fovyUnitsLabel = QtWidgets.QLabel(self.OutputBox)
        self.fovyUnitsLabel.setObjectName("fovyUnitsLabel")
        self.gridLayout_4.addWidget(self.fovyUnitsLabel, 1, 2, 1, 1)
        self.fovyDegUnitsLabel = QtWidgets.QLabel(self.OutputBox)
        self.fovyDegUnitsLabel.setObjectName("fovyDegUnitsLabel")
        self.gridLayout_4.addWidget(self.fovyDegUnitsLabel, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 10, 1, 1)
        self.fovxDegValueLabel = QtWidgets.QLabel(self.OutputBox)
        self.fovxDegValueLabel.setObjectName("fovxDegValueLabel")
        self.gridLayout_4.addWidget(self.fovxDegValueLabel, 0, 3, 1, 1)
        self.framerateLabel = QtWidgets.QLabel(self.OutputBox)
        self.framerateLabel.setObjectName("framerateLabel")
        self.gridLayout_4.addWidget(self.framerateLabel, 0, 6, 1, 1)
        self.exposureValueLabel = QtWidgets.QLabel(self.OutputBox)
        self.exposureValueLabel.setMinimumSize(QtCore.QSize(40, 0))
        self.exposureValueLabel.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.exposureValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exposureValueLabel.setObjectName("exposureValueLabel")
        self.gridLayout_4.addWidget(self.exposureValueLabel, 3, 1, 1, 1)
        self.apertureValueLabel = QtWidgets.QLabel(self.OutputBox)
        self.apertureValueLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.apertureValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.apertureValueLabel.setObjectName("apertureValueLabel")
        self.gridLayout_4.addWidget(self.apertureValueLabel, 2, 1, 1, 1)
        self.avgImageValueUnitsLabel = QtWidgets.QLabel(self.OutputBox)
        self.avgImageValueUnitsLabel.setObjectName("avgImageValueUnitsLabel")
        self.gridLayout_4.addWidget(self.avgImageValueUnitsLabel, 1, 9, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 4, 0, 1, 1)
        self.framerateValueLabel = QtWidgets.QLabel(self.OutputBox)
        self.framerateValueLabel.setMinimumSize(QtCore.QSize(20, 0))
        self.framerateValueLabel.setObjectName("framerateValueLabel")
        self.gridLayout_4.addWidget(self.framerateValueLabel, 0, 7, 1, 1)
        self.FOVyLabel = QtWidgets.QLabel(self.OutputBox)
        self.FOVyLabel.setObjectName("FOVyLabel")
        self.gridLayout_4.addWidget(self.FOVyLabel, 1, 0, 1, 1)
        self.fovxDegUnitsLabel = QtWidgets.QLabel(self.OutputBox)
        self.fovxDegUnitsLabel.setObjectName("fovxDegUnitsLabel")
        self.gridLayout_4.addWidget(self.fovxDegUnitsLabel, 0, 4, 1, 1)
        self.fovxUnitsLabel = QtWidgets.QLabel(self.OutputBox)
        self.fovxUnitsLabel.setObjectName("fovxUnitsLabel")
        self.gridLayout_4.addWidget(self.fovxUnitsLabel, 0, 2, 1, 1)
        self.framerateUnitsLabel = QtWidgets.QLabel(self.OutputBox)
        self.framerateUnitsLabel.setObjectName("framerateUnitsLabel")
        self.gridLayout_4.addWidget(self.framerateUnitsLabel, 0, 9, 1, 1)
        self.exposureLabel = QtWidgets.QLabel(self.OutputBox)
        self.exposureLabel.setObjectName("exposureLabel")
        self.gridLayout_4.addWidget(self.exposureLabel, 3, 0, 1, 1)
        self.apertureLabel = QtWidgets.QLabel(self.OutputBox)
        self.apertureLabel.setObjectName("apertureLabel")
        self.gridLayout_4.addWidget(self.apertureLabel, 2, 0, 1, 1)
        self.FOVxLabel = QtWidgets.QLabel(self.OutputBox)
        self.FOVxLabel.setObjectName("FOVxLabel")
        self.gridLayout_4.addWidget(self.FOVxLabel, 0, 0, 1, 1)
        self.fovxValueLabel = QtWidgets.QLabel(self.OutputBox)
        self.fovxValueLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.fovxValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fovxValueLabel.setObjectName("fovxValueLabel")
        self.gridLayout_4.addWidget(self.fovxValueLabel, 0, 1, 1, 1)
        self.imgAvgValueLabel = QtWidgets.QLabel(self.OutputBox)
        self.imgAvgValueLabel.setObjectName("imgAvgValueLabel")
        self.gridLayout_4.addWidget(self.imgAvgValueLabel, 1, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 5, 1, 1)
        self.WaterAttenuationBox = QtWidgets.QGroupBox(self.designerpage)
        self.WaterAttenuationBox.setGeometry(QtCore.QRect(400, 11, 251, 287))
        self.WaterAttenuationBox.setObjectName("WaterAttenuationBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.WaterAttenuationBox)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.watertypeLabel = QtWidgets.QLabel(self.WaterAttenuationBox)
        self.watertypeLabel.setObjectName("watertypeLabel")
        self.horizontalLayout_3.addWidget(self.watertypeLabel)
        self.waterTypeComboBox = QtWidgets.QComboBox(self.WaterAttenuationBox)
        self.waterTypeComboBox.setObjectName("waterTypeComboBox")
        self.waterTypeComboBox.addItem("")
        self.waterTypeComboBox.addItem("")
        self.waterTypeComboBox.addItem("")
        self.waterTypeComboBox.addItem("")
        self.waterTypeComboBox.addItem("")
        self.waterTypeComboBox.addItem("")
        self.waterTypeComboBox.addItem("")
        self.waterTypeComboBox.addItem("")
        self.waterTypeComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.waterTypeComboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.waterStackedWidget = QtWidgets.QStackedWidget(self.WaterAttenuationBox)
        self.waterStackedWidget.setObjectName("waterStackedWidget")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.loadWaterProfileButton = QtWidgets.QPushButton(self.page_8)
        self.loadWaterProfileButton.setObjectName("loadWaterProfileButton")
        self.verticalLayout_11.addWidget(self.loadWaterProfileButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.waterStackedWidget.addWidget(self.page_8)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.jerlovITextLabel = QtWidgets.QLabel(self.page_6)
        self.jerlovITextLabel.setWordWrap(True)
        self.jerlovITextLabel.setObjectName("jerlovITextLabel")
        self.verticalLayout_9.addWidget(self.jerlovITextLabel)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.waterStackedWidget.addWidget(self.page_6)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.waterStackedWidget.addWidget(self.page_11)
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.waterStackedWidget.addWidget(self.page_14)
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.waterStackedWidget.addWidget(self.page_15)
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setObjectName("page_16")
        self.waterStackedWidget.addWidget(self.page_16)
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setObjectName("page_17")
        self.waterStackedWidget.addWidget(self.page_17)
        self.page_18 = QtWidgets.QWidget()
        self.page_18.setObjectName("page_18")
        self.waterStackedWidget.addWidget(self.page_18)
        self.page_19 = QtWidgets.QWidget()
        self.page_19.setObjectName("page_19")
        self.waterStackedWidget.addWidget(self.page_19)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.page_7)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.label_3)
        self.waterStackedWidget.addWidget(self.page_7)
        self.verticalLayout_4.addWidget(self.waterStackedWidget)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem5)
        self.waterModelInfoButton = QtWidgets.QPushButton(self.WaterAttenuationBox)
        self.waterModelInfoButton.setObjectName("waterModelInfoButton")
        self.verticalLayout_4.addWidget(self.waterModelInfoButton)
        self.LensBox = QtWidgets.QGroupBox(self.designerpage)
        self.LensBox.setGeometry(QtCore.QRect(666, 11, 347, 287))
        self.LensBox.setObjectName("LensBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.LensBox)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LensComboBox = QtWidgets.QComboBox(self.LensBox)
        self.LensComboBox.setObjectName("LensComboBox")
        self.LensComboBox.addItem("")
        self.LensComboBox.addItem("")
        self.gridLayout_2.addWidget(self.LensComboBox, 0, 1, 1, 1)
        self.lensTypeLabel = QtWidgets.QLabel(self.LensBox)
        self.lensTypeLabel.setObjectName("lensTypeLabel")
        self.gridLayout_2.addWidget(self.lensTypeLabel, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.lensStackedWidget = QtWidgets.QStackedWidget(self.LensBox)
        self.lensStackedWidget.setMinimumSize(QtCore.QSize(3, 0))
        self.lensStackedWidget.setObjectName("lensStackedWidget")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lensLoadFileButton = QtWidgets.QPushButton(self.page_9)
        self.lensLoadFileButton.setObjectName("lensLoadFileButton")
        self.verticalLayout_8.addWidget(self.lensLoadFileButton)
        self.lensLoadedFileLabel = QtWidgets.QLabel(self.page_9)
        self.lensLoadedFileLabel.setObjectName("lensLoadedFileLabel")
        self.verticalLayout_8.addWidget(self.lensLoadedFileLabel)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.focalLengthLabel = QtWidgets.QLabel(self.page_9)
        self.focalLengthLabel.setObjectName("focalLengthLabel")
        self.horizontalLayout_6.addWidget(self.focalLengthLabel)
        self.focalLengthValueLabel = QtWidgets.QLabel(self.page_9)
        self.focalLengthValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.focalLengthValueLabel.setObjectName("focalLengthValueLabel")
        self.horizontalLayout_6.addWidget(self.focalLengthValueLabel)
        self.focalLengthUnitsLabel = QtWidgets.QLabel(self.page_9)
        self.focalLengthUnitsLabel.setObjectName("focalLengthUnitsLabel")
        self.horizontalLayout_6.addWidget(self.focalLengthUnitsLabel)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.lensStackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_10)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.focalLengthLabel_2 = QtWidgets.QLabel(self.page_10)
        self.focalLengthLabel_2.setObjectName("focalLengthLabel_2")
        self.gridLayout_10.addWidget(self.focalLengthLabel_2, 0, 0, 1, 1)
        self.transmittanceLabel = QtWidgets.QLabel(self.page_10)
        self.transmittanceLabel.setObjectName("transmittanceLabel")
        self.gridLayout_10.addWidget(self.transmittanceLabel, 2, 0, 1, 1)
        self.transmittanceSlider = QtWidgets.QSlider(self.page_10)
        self.transmittanceSlider.setMinimumSize(QtCore.QSize(100, 0))
        self.transmittanceSlider.setMaximum(100)
        self.transmittanceSlider.setSliderPosition(90)
        self.transmittanceSlider.setTracking(True)
        self.transmittanceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.transmittanceSlider.setObjectName("transmittanceSlider")
        self.gridLayout_10.addWidget(self.transmittanceSlider, 2, 1, 1, 1)
        self.focalLenthSliderUnitsLabel = QtWidgets.QLabel(self.page_10)
        self.focalLenthSliderUnitsLabel.setObjectName("focalLenthSliderUnitsLabel")
        self.gridLayout_10.addWidget(self.focalLenthSliderUnitsLabel, 0, 4, 1, 1)
        self.transmittanceValueLabel = QtWidgets.QLabel(self.page_10)
        self.transmittanceValueLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.transmittanceValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.transmittanceValueLabel.setObjectName("transmittanceValueLabel")
        self.gridLayout_10.addWidget(self.transmittanceValueLabel, 2, 3, 1, 1)
        self.transmittanceUnitsLabel = QtWidgets.QLabel(self.page_10)
        self.transmittanceUnitsLabel.setObjectName("transmittanceUnitsLabel")
        self.gridLayout_10.addWidget(self.transmittanceUnitsLabel, 2, 4, 1, 1)
        self.focalLengthSliderValueLabel = QtWidgets.QLabel(self.page_10)
        self.focalLengthSliderValueLabel.setMinimumSize(QtCore.QSize(25, 0))
        self.focalLengthSliderValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.focalLengthSliderValueLabel.setObjectName("focalLengthSliderValueLabel")
        self.gridLayout_10.addWidget(self.focalLengthSliderValueLabel, 0, 3, 1, 1)
        self.focalLengthSlider = QtWidgets.QSlider(self.page_10)
        self.focalLengthSlider.setMinimumSize(QtCore.QSize(100, 0))
        self.focalLengthSlider.setMinimum(1)
        self.focalLengthSlider.setMaximum(200)
        self.focalLengthSlider.setProperty("value", 8)
        self.focalLengthSlider.setTracking(True)
        self.focalLengthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.focalLengthSlider.setObjectName("focalLengthSlider")
        self.gridLayout_10.addWidget(self.focalLengthSlider, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 0, 2, 1, 1)
        self.lensStackedWidget.addWidget(self.page_10)
        self.verticalLayout_5.addWidget(self.lensStackedWidget)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.effectiveFocalLengthLabel = QtWidgets.QLabel(self.LensBox)
        self.effectiveFocalLengthLabel.setObjectName("effectiveFocalLengthLabel")
        self.horizontalLayout_4.addWidget(self.effectiveFocalLengthLabel)
        self.effectiveFocalLengthValueLabel = QtWidgets.QLabel(self.LensBox)
        self.effectiveFocalLengthValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.effectiveFocalLengthValueLabel.setObjectName("effectiveFocalLengthValueLabel")
        self.horizontalLayout_4.addWidget(self.effectiveFocalLengthValueLabel)
        self.effectiveFocalLengthUnitsLabel = QtWidgets.QLabel(self.LensBox)
        self.effectiveFocalLengthUnitsLabel.setObjectName("effectiveFocalLengthUnitsLabel")
        self.horizontalLayout_4.addWidget(self.effectiveFocalLengthUnitsLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.lensInfoButton = QtWidgets.QPushButton(self.LensBox)
        self.lensInfoButton.setObjectName("lensInfoButton")
        self.verticalLayout_5.addWidget(self.lensInfoButton)
        self.SensorBox = QtWidgets.QGroupBox(self.designerpage)
        self.SensorBox.setGeometry(QtCore.QRect(1028, 11, 208, 287))
        self.SensorBox.setObjectName("SensorBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.SensorBox)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cameraTypeLabel = QtWidgets.QLabel(self.SensorBox)
        self.cameraTypeLabel.setObjectName("cameraTypeLabel")
        self.horizontalLayout_5.addWidget(self.cameraTypeLabel)
        self.cameraComboBox = QtWidgets.QComboBox(self.SensorBox)
        self.cameraComboBox.setObjectName("cameraComboBox")
        self.cameraComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.cameraComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.cameraStackedWidget = QtWidgets.QStackedWidget(self.SensorBox)
        self.cameraStackedWidget.setObjectName("cameraStackedWidget")
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_12)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.cameraLoadFileButton = QtWidgets.QPushButton(self.page_12)
        self.cameraLoadFileButton.setObjectName("cameraLoadFileButton")
        self.gridLayout_11.addWidget(self.cameraLoadFileButton, 0, 0, 1, 1)
        self.cameraLoadedFileLabel = QtWidgets.QLabel(self.page_12)
        self.cameraLoadedFileLabel.setObjectName("cameraLoadedFileLabel")
        self.gridLayout_11.addWidget(self.cameraLoadedFileLabel, 1, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.resolutionyLabel = QtWidgets.QLabel(self.page_12)
        self.resolutionyLabel.setObjectName("resolutionyLabel")
        self.gridLayout_9.addWidget(self.resolutionyLabel, 3, 0, 1, 1)
        self.resolutionxLabel = QtWidgets.QLabel(self.page_12)
        self.resolutionxLabel.setObjectName("resolutionxLabel")
        self.gridLayout_9.addWidget(self.resolutionxLabel, 2, 0, 1, 1)
        self.pixelSizeLabel = QtWidgets.QLabel(self.page_12)
        self.pixelSizeLabel.setObjectName("pixelSizeLabel")
        self.gridLayout_9.addWidget(self.pixelSizeLabel, 1, 0, 1, 1)
        self.pixelSizeUnitsLabel = QtWidgets.QLabel(self.page_12)
        self.pixelSizeUnitsLabel.setObjectName("pixelSizeUnitsLabel")
        self.gridLayout_9.addWidget(self.pixelSizeUnitsLabel, 1, 2, 1, 1)
        self.pixelSizeValueLabel = QtWidgets.QLabel(self.page_12)
        self.pixelSizeValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pixelSizeValueLabel.setObjectName("pixelSizeValueLabel")
        self.gridLayout_9.addWidget(self.pixelSizeValueLabel, 1, 1, 1, 1)
        self.resolutionxValueLabel = QtWidgets.QLabel(self.page_12)
        self.resolutionxValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resolutionxValueLabel.setObjectName("resolutionxValueLabel")
        self.gridLayout_9.addWidget(self.resolutionxValueLabel, 2, 1, 1, 1)
        self.resolutionxUnitsLabel = QtWidgets.QLabel(self.page_12)
        self.resolutionxUnitsLabel.setObjectName("resolutionxUnitsLabel")
        self.gridLayout_9.addWidget(self.resolutionxUnitsLabel, 2, 2, 1, 1)
        self.resolutionyValueLabel = QtWidgets.QLabel(self.page_12)
        self.resolutionyValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resolutionyValueLabel.setObjectName("resolutionyValueLabel")
        self.gridLayout_9.addWidget(self.resolutionyValueLabel, 3, 1, 1, 1)
        self.resolutionyUnitsLabel = QtWidgets.QLabel(self.page_12)
        self.resolutionyUnitsLabel.setObjectName("resolutionyUnitsLabel")
        self.gridLayout_9.addWidget(self.resolutionyUnitsLabel, 3, 2, 1, 1)
        self.sensorNameLabel_2 = QtWidgets.QLabel(self.page_12)
        self.sensorNameLabel_2.setObjectName("sensorNameLabel_2")
        self.gridLayout_9.addWidget(self.sensorNameLabel_2, 0, 0, 1, 1)
        self.sensorNameLabel = QtWidgets.QLabel(self.page_12)
        self.sensorNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sensorNameLabel.setObjectName("sensorNameLabel")
        self.gridLayout_9.addWidget(self.sensorNameLabel, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_9, 2, 0, 1, 1)
        self.cameraStackedWidget.addWidget(self.page_12)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.cameraStackedWidget.addWidget(self.page_13)
        self.verticalLayout_6.addWidget(self.cameraStackedWidget)
        self.cameraInfoButton = QtWidgets.QPushButton(self.SensorBox)
        self.cameraInfoButton.setObjectName("cameraInfoButton")
        self.verticalLayout_6.addWidget(self.cameraInfoButton)
        self.LightBox = QtWidgets.QGroupBox(self.designerpage)
        self.LightBox.setEnabled(True)
        self.LightBox.setGeometry(QtCore.QRect(1, 11, 384, 287))
        self.LightBox.setFlat(False)
        self.LightBox.setCheckable(False)
        self.LightBox.setObjectName("LightBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LightBox)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lightTypeLabel = QtWidgets.QLabel(self.LightBox)
        self.lightTypeLabel.setObjectName("lightTypeLabel")
        self.horizontalLayout_2.addWidget(self.lightTypeLabel)
        self.LightsComboBox = QtWidgets.QComboBox(self.LightBox)
        self.LightsComboBox.setObjectName("LightsComboBox")
        self.LightsComboBox.addItem("")
        self.LightsComboBox.addItem("")
        self.LightsComboBox.addItem("")
        self.LightsComboBox.addItem("")
        self.LightsComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.LightsComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.lightStackedWidget = QtWidgets.QStackedWidget(self.LightBox)
        self.lightStackedWidget.setObjectName("lightStackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lightsLoadFileButton = QtWidgets.QPushButton(self.page_2)
        self.lightsLoadFileButton.setObjectName("lightsLoadFileButton")
        self.verticalLayout_7.addWidget(self.lightsLoadFileButton)
        self.lightsLoadedFileLabel = QtWidgets.QLabel(self.page_2)
        self.lightsLoadedFileLabel.setObjectName("lightsLoadedFileLabel")
        self.verticalLayout_7.addWidget(self.lightsLoadedFileLabel)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem9)
        self.lightStackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 3, 0, 1, 1)
        self.lightLedLabel = QtWidgets.QLabel(self.page)
        self.lightLedLabel.setObjectName("lightLedLabel")
        self.gridLayout.addWidget(self.lightLedLabel, 0, 0, 1, 1)
        self.ledSpectrumLabel = QtWidgets.QLabel(self.page)
        self.ledSpectrumLabel.setWordWrap(True)
        self.ledSpectrumLabel.setObjectName("ledSpectrumLabel")
        self.gridLayout.addWidget(self.ledSpectrumLabel, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.luminousFluxLabel = QtWidgets.QLabel(self.page)
        self.luminousFluxLabel.setObjectName("luminousFluxLabel")
        self.gridLayout_5.addWidget(self.luminousFluxLabel, 0, 0, 1, 1)
        self.beamAngleSlider = QtWidgets.QSlider(self.page)
        self.beamAngleSlider.setMaximumSize(QtCore.QSize(100, 16777215))
        self.beamAngleSlider.setMinimum(1)
        self.beamAngleSlider.setMaximum(90)
        self.beamAngleSlider.setProperty("value", 15)
        self.beamAngleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.beamAngleSlider.setObjectName("beamAngleSlider")
        self.gridLayout_5.addWidget(self.beamAngleSlider, 1, 1, 1, 1)
        self.beamAngleLabel = QtWidgets.QLabel(self.page)
        self.beamAngleLabel.setObjectName("beamAngleLabel")
        self.gridLayout_5.addWidget(self.beamAngleLabel, 1, 0, 1, 1)
        self.beamAngleValueLabel = QtWidgets.QLabel(self.page)
        self.beamAngleValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.beamAngleValueLabel.setObjectName("beamAngleValueLabel")
        self.gridLayout_5.addWidget(self.beamAngleValueLabel, 1, 2, 1, 1)
        self.luminousFluxLineEdit = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.luminousFluxLineEdit.sizePolicy().hasHeightForWidth())
        self.luminousFluxLineEdit.setSizePolicy(sizePolicy)
        self.luminousFluxLineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.luminousFluxLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.luminousFluxLineEdit.setMaxLength(10)
        self.luminousFluxLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.luminousFluxLineEdit.setObjectName("luminousFluxLineEdit")
        self.gridLayout_5.addWidget(self.luminousFluxLineEdit, 0, 1, 1, 1)
        self.beamAngleUnitsLabel = QtWidgets.QLabel(self.page)
        self.beamAngleUnitsLabel.setObjectName("beamAngleUnitsLabel")
        self.gridLayout_5.addWidget(self.beamAngleUnitsLabel, 1, 3, 1, 1)
        self.liminousFluxUnitsLabel = QtWidgets.QLabel(self.page)
        self.liminousFluxUnitsLabel.setObjectName("liminousFluxUnitsLabel")
        self.gridLayout_5.addWidget(self.liminousFluxUnitsLabel, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 2, 0, 1, 1)
        self.lightStackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lightXenonLabel = QtWidgets.QLabel(self.page_3)
        self.lightXenonLabel.setObjectName("lightXenonLabel")
        self.gridLayout_7.addWidget(self.lightXenonLabel, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem11, 1, 0, 1, 1)
        self.lightStackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lightTungstenLabel = QtWidgets.QLabel(self.page_4)
        self.lightTungstenLabel.setObjectName("lightTungstenLabel")
        self.gridLayout_6.addWidget(self.lightTungstenLabel, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem12, 1, 0, 1, 1)
        self.lightStackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lightHalogenLabel = QtWidgets.QLabel(self.page_5)
        self.lightHalogenLabel.setObjectName("lightHalogenLabel")
        self.gridLayout_8.addWidget(self.lightHalogenLabel, 0, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem13, 1, 0, 1, 1)
        self.lightStackedWidget.addWidget(self.page_5)
        self.verticalLayout_2.addWidget(self.lightStackedWidget)
        self.lightsInfoButton = QtWidgets.QPushButton(self.LightBox)
        self.lightsInfoButton.setObjectName("lightsInfoButton")
        self.verticalLayout_2.addWidget(self.lightsInfoButton)
        self.SceneBox = QtWidgets.QGroupBox(self.designerpage)
        self.SceneBox.setGeometry(QtCore.QRect(0, 314, 1237, 131))
        self.SceneBox.setObjectName("SceneBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.SceneBox)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.speedSlider = QtWidgets.QSlider(self.SceneBox)
        self.speedSlider.setMaximum(400)
        self.speedSlider.setProperty("value", 50)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName("speedSlider")
        self.gridLayout_3.addWidget(self.speedSlider, 2, 1, 1, 1)
        self.dofLabel = QtWidgets.QLabel(self.SceneBox)
        self.dofLabel.setObjectName("dofLabel")
        self.gridLayout_3.addWidget(self.dofLabel, 1, 5, 1, 1)
        self.overlapValueLabel = QtWidgets.QLabel(self.SceneBox)
        self.overlapValueLabel.setMinimumSize(QtCore.QSize(40, 0))
        self.overlapValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.overlapValueLabel.setObjectName("overlapValueLabel")
        self.gridLayout_3.addWidget(self.overlapValueLabel, 1, 2, 1, 1)
        self.speedLabel = QtWidgets.QLabel(self.SceneBox)
        self.speedLabel.setObjectName("speedLabel")
        self.gridLayout_3.addWidget(self.speedLabel, 2, 0, 1, 1)
        self.altitudeLabel = QtWidgets.QLabel(self.SceneBox)
        self.altitudeLabel.setMinimumSize(QtCore.QSize(40, 0))
        self.altitudeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.altitudeLabel.setObjectName("altitudeLabel")
        self.gridLayout_3.addWidget(self.altitudeLabel, 0, 2, 1, 1)
        self.overlapLabel = QtWidgets.QLabel(self.SceneBox)
        self.overlapLabel.setObjectName("overlapLabel")
        self.gridLayout_3.addWidget(self.overlapLabel, 1, 0, 1, 1)
        self.altitudeLabel_2 = QtWidgets.QLabel(self.SceneBox)
        self.altitudeLabel_2.setObjectName("altitudeLabel_2")
        self.gridLayout_3.addWidget(self.altitudeLabel_2, 0, 0, 1, 1)
        self.overlapSlider = QtWidgets.QSlider(self.SceneBox)
        self.overlapSlider.setProperty("value", 25)
        self.overlapSlider.setOrientation(QtCore.Qt.Horizontal)
        self.overlapSlider.setObjectName("overlapSlider")
        self.gridLayout_3.addWidget(self.overlapSlider, 1, 1, 1, 1)
        self.overlapUnitsLabel = QtWidgets.QLabel(self.SceneBox)
        self.overlapUnitsLabel.setObjectName("overlapUnitsLabel")
        self.gridLayout_3.addWidget(self.overlapUnitsLabel, 1, 3, 1, 1)
        self.speedValueLabel = QtWidgets.QLabel(self.SceneBox)
        self.speedValueLabel.setMinimumSize(QtCore.QSize(40, 0))
        self.speedValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speedValueLabel.setObjectName("speedValueLabel")
        self.gridLayout_3.addWidget(self.speedValueLabel, 2, 2, 1, 1)
        self.speedUnitsLabel = QtWidgets.QLabel(self.SceneBox)
        self.speedUnitsLabel.setObjectName("speedUnitsLabel")
        self.gridLayout_3.addWidget(self.speedUnitsLabel, 2, 3, 1, 1)
        self.altitudeUnitsLabel = QtWidgets.QLabel(self.SceneBox)
        self.altitudeUnitsLabel.setObjectName("altitudeUnitsLabel")
        self.gridLayout_3.addWidget(self.altitudeUnitsLabel, 0, 3, 1, 1)
        self.altitudeSlider = QtWidgets.QSlider(self.SceneBox)
        self.altitudeSlider.setMaximum(1500)
        self.altitudeSlider.setSingleStep(1)
        self.altitudeSlider.setProperty("value", 150)
        self.altitudeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.altitudeSlider.setObjectName("altitudeSlider")
        self.gridLayout_3.addWidget(self.altitudeSlider, 0, 1, 1, 1)
        self.dofValueLabel = QtWidgets.QLabel(self.SceneBox)
        self.dofValueLabel.setMinimumSize(QtCore.QSize(25, 0))
        self.dofValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dofValueLabel.setObjectName("dofValueLabel")
        self.gridLayout_3.addWidget(self.dofValueLabel, 1, 7, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem14, 0, 4, 1, 1)
        self.cameraOrientationLabel = QtWidgets.QLabel(self.SceneBox)
        self.cameraOrientationLabel.setObjectName("cameraOrientationLabel")
        self.gridLayout_3.addWidget(self.cameraOrientationLabel, 0, 10, 1, 1)
        self.dofUnitsLabel = QtWidgets.QLabel(self.SceneBox)
        self.dofUnitsLabel.setObjectName("dofUnitsLabel")
        self.gridLayout_3.addWidget(self.dofUnitsLabel, 1, 8, 1, 1)
        self.cameraOrientationCombobox = QtWidgets.QComboBox(self.SceneBox)
        self.cameraOrientationCombobox.setObjectName("cameraOrientationCombobox")
        self.cameraOrientationCombobox.addItem("")
        self.cameraOrientationCombobox.addItem("")
        self.gridLayout_3.addWidget(self.cameraOrientationCombobox, 0, 12, 1, 1)
        self.motionBlurSlider = QtWidgets.QSlider(self.SceneBox)
        self.motionBlurSlider.setSliderPosition(2)
        self.motionBlurSlider.setOrientation(QtCore.Qt.Horizontal)
        self.motionBlurSlider.setObjectName("motionBlurSlider")
        self.gridLayout_3.addWidget(self.motionBlurSlider, 0, 6, 1, 1)
        self.motionBlurValueLabel = QtWidgets.QLabel(self.SceneBox)
        self.motionBlurValueLabel.setMinimumSize(QtCore.QSize(25, 0))
        self.motionBlurValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.motionBlurValueLabel.setObjectName("motionBlurValueLabel")
        self.gridLayout_3.addWidget(self.motionBlurValueLabel, 0, 7, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 0, 9, 1, 1)
        self.motionBlurLabel = QtWidgets.QLabel(self.SceneBox)
        self.motionBlurLabel.setObjectName("motionBlurLabel")
        self.gridLayout_3.addWidget(self.motionBlurLabel, 0, 5, 1, 1)
        self.motionBlurUnitsLabel = QtWidgets.QLabel(self.SceneBox)
        self.motionBlurUnitsLabel.setObjectName("motionBlurUnitsLabel")
        self.gridLayout_3.addWidget(self.motionBlurUnitsLabel, 0, 8, 1, 1)
        self.dofSlider = QtWidgets.QSlider(self.SceneBox)
        self.dofSlider.setMinimum(1)
        self.dofSlider.setMaximum(600)
        self.dofSlider.setProperty("value", 100)
        self.dofSlider.setOrientation(QtCore.Qt.Horizontal)
        self.dofSlider.setObjectName("dofSlider")
        self.gridLayout_3.addWidget(self.dofSlider, 1, 6, 1, 1)
        self.bottomTypeLabel = QtWidgets.QLabel(self.SceneBox)
        self.bottomTypeLabel.setObjectName("bottomTypeLabel")
        self.gridLayout_3.addWidget(self.bottomTypeLabel, 2, 10, 1, 1)
        self.bottomTypeCombo = QtWidgets.QComboBox(self.SceneBox)
        self.bottomTypeCombo.setObjectName("bottomTypeCombo")
        self.bottomTypeCombo.addItem("")
        self.bottomTypeCombo.addItem("")
        self.bottomTypeCombo.addItem("")
        self.bottomTypeCombo.addItem("")
        self.bottomTypeCombo.addItem("")
        self.gridLayout_3.addWidget(self.bottomTypeCombo, 2, 12, 1, 1)
        self.viewportCombobox = QtWidgets.QComboBox(self.SceneBox)
        self.viewportCombobox.setObjectName("viewportCombobox")
        self.viewportCombobox.addItem("")
        self.viewportCombobox.addItem("")
        self.gridLayout_3.addWidget(self.viewportCombobox, 1, 12, 1, 1)
        self.housingLabel = QtWidgets.QLabel(self.SceneBox)
        self.housingLabel.setObjectName("housingLabel")
        self.gridLayout_3.addWidget(self.housingLabel, 1, 10, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.designerpage)
        self.line_2.setGeometry(QtCore.QRect(0, 305, 1237, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.designerpage)
        self.line_4.setGeometry(QtCore.QRect(0, 451, 1237, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.widget = QtWidgets.QWidget(self.designerpage)
        self.widget.setGeometry(QtCore.QRect(10, 610, 1237, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_7.setContentsMargins(11, 0, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.saveButton = QtWidgets.QPushButton(self.widget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_7.addWidget(self.saveButton)
        self.loadButton = QtWidgets.QPushButton(self.widget)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_7.addWidget(self.loadButton)
        self.exportButton = QtWidgets.QPushButton(self.widget)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout_7.addWidget(self.exportButton)
        self.modesStack.addWidget(self.designerpage)
        self.page_21 = QtWidgets.QWidget()
        self.page_21.setObjectName("page_21")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.page_21)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(160, 130, 531, 311))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label.setObjectName("label")
        self.verticalLayout_12.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_3)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_12.addWidget(self.listWidget)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_8.addWidget(self.pushButton_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget_3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_12.addWidget(self.line)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout.addLayout(self.horizontalLayout_10)
        self.plotWidget = QtWidgets.QWidget(self.horizontalLayoutWidget_3)
        self.plotWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.plotWidget.setObjectName("plotWidget")
        self.horizontalLayout.addWidget(self.plotWidget)
        self.horizontalLayout_9.addLayout(self.horizontalLayout)
        self.modesStack.addWidget(self.page_21)
        self.verticalLayout.addWidget(self.modesStack)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1255, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuUnderwater_Optical_Systems_Calculator = QtWidgets.QMenu(self.menuBar)
        self.menuUnderwater_Optical_Systems_Calculator.setObjectName("menuUnderwater_Optical_Systems_Calculator")
        self.menuFIle = QtWidgets.QMenu(self.menuBar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuMode = QtWidgets.QMenu(self.menuBar)
        self.menuMode.setObjectName("menuMode")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionDesigner = QtWidgets.QAction(MainWindow)
        self.actionDesigner.setObjectName("actionDesigner")
        self.actionCompare_Sensors = QtWidgets.QAction(MainWindow)
        self.actionCompare_Sensors.setObjectName("actionCompare_Sensors")
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.actionSave)
        self.menuFIle.addAction(self.actionLoad)
        self.menuMode.addAction(self.actionDesigner)
        self.menuMode.addAction(self.actionCompare_Sensors)
        self.menuBar.addAction(self.menuUnderwater_Optical_Systems_Calculator.menuAction())
        self.menuBar.addAction(self.menuFIle.menuAction())
        self.menuBar.addAction(self.menuMode.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.waterStackedWidget.setCurrentIndex(0)
        self.lensStackedWidget.setCurrentIndex(0)
        self.cameraStackedWidget.setCurrentIndex(0)
        self.lightStackedWidget.setCurrentIndex(0)
        self.LightsComboBox.currentIndexChanged['int'].connect(self.lightStackedWidget.setCurrentIndex)
        self.LensComboBox.currentIndexChanged['int'].connect(self.lensStackedWidget.setCurrentIndex)
        self.altitudeSlider.valueChanged['int'].connect(self.altitudeLabel.setNum)
        self.overlapSlider.valueChanged['int'].connect(self.overlapValueLabel.setNum)
        self.motionBlurSlider.valueChanged['int'].connect(self.motionBlurValueLabel.setNum)
        self.speedSlider.valueChanged['int'].connect(self.speedValueLabel.setNum)
        self.dofSlider.valueChanged['int'].connect(self.dofValueLabel.setNum)
        self.transmittanceSlider.valueChanged['int'].connect(self.transmittanceValueLabel.setNum)
        self.focalLengthSlider.valueChanged['int'].connect(self.focalLengthSliderValueLabel.setNum)
        self.beamAngleSlider.valueChanged['int'].connect(self.beamAngleValueLabel.setNum)
        self.waterTypeComboBox.currentIndexChanged['int'].connect(self.waterStackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Underwater Optical Systems Calculator"))
        self.OutputBox.setTitle(_translate("MainWindow", "Output"))
        self.exposureUnitsLabel.setText(_translate("MainWindow", "ms"))
        self.apertureUnitsLabel.setText(_translate("MainWindow", "f-Number"))
        self.fovyValueLabel.setText(_translate("MainWindow", "0"))
        self.fovyDegValueLabel.setText(_translate("MainWindow", "0"))
        self.avgImgValueValueLabel.setText(_translate("MainWindow", "0"))
        self.fovyUnitsLabel.setText(_translate("MainWindow", "m"))
        self.fovyDegUnitsLabel.setText(_translate("MainWindow", "deg"))
        self.fovxDegValueLabel.setText(_translate("MainWindow", "0"))
        self.framerateLabel.setText(_translate("MainWindow", "Framerate:"))
        self.exposureValueLabel.setText(_translate("MainWindow", "0"))
        self.apertureValueLabel.setText(_translate("MainWindow", "0"))
        self.avgImageValueUnitsLabel.setText(_translate("MainWindow", "%"))
        self.framerateValueLabel.setText(_translate("MainWindow", "0"))
        self.FOVyLabel.setText(_translate("MainWindow", "FOV y:"))
        self.fovxDegUnitsLabel.setText(_translate("MainWindow", "deg"))
        self.fovxUnitsLabel.setText(_translate("MainWindow", "m"))
        self.framerateUnitsLabel.setText(_translate("MainWindow", "Hz"))
        self.exposureLabel.setText(_translate("MainWindow", "Max Exposure:"))
        self.apertureLabel.setText(_translate("MainWindow", "Min. Aperture:"))
        self.FOVxLabel.setText(_translate("MainWindow", "FOV x:"))
        self.fovxValueLabel.setText(_translate("MainWindow", "0"))
        self.imgAvgValueLabel.setText(_translate("MainWindow", "Avg Image Intensity:"))
        self.WaterAttenuationBox.setTitle(_translate("MainWindow", "Underwater Attenuation"))
        self.watertypeLabel.setText(_translate("MainWindow", "Water type:"))
        self.waterTypeComboBox.setItemText(0, _translate("MainWindow", "Custom"))
        self.waterTypeComboBox.setItemText(1, _translate("MainWindow", "Jerlov I"))
        self.waterTypeComboBox.setItemText(2, _translate("MainWindow", "Jerlov II"))
        self.waterTypeComboBox.setItemText(3, _translate("MainWindow", "Jerlov III"))
        self.waterTypeComboBox.setItemText(4, _translate("MainWindow", "Jerlov IC"))
        self.waterTypeComboBox.setItemText(5, _translate("MainWindow", "Jerlov 3C"))
        self.waterTypeComboBox.setItemText(6, _translate("MainWindow", "Jerlov 5C"))
        self.waterTypeComboBox.setItemText(7, _translate("MainWindow", "Jerlov 7C"))
        self.waterTypeComboBox.setItemText(8, _translate("MainWindow", "Jerlov 9C"))
        self.loadWaterProfileButton.setText(_translate("MainWindow", "Load Profile"))
        self.jerlovITextLabel.setText(_translate("MainWindow", "Jerlov I  type waters are very clear oceanic waters"))
        self.label_3.setText(_translate("MainWindow", "THis is a placeholder label tose"))
        self.waterModelInfoButton.setText(_translate("MainWindow", "Info"))
        self.LensBox.setTitle(_translate("MainWindow", "Lens"))
        self.LensComboBox.setItemText(0, _translate("MainWindow", "Custom "))
        self.LensComboBox.setItemText(1, _translate("MainWindow", "Generic"))
        self.lensTypeLabel.setText(_translate("MainWindow", "Lens Type:"))
        self.lensLoadFileButton.setText(_translate("MainWindow", "Load Lens"))
        self.lensLoadedFileLabel.setText(_translate("MainWindow", "No File Loaded"))
        self.focalLengthLabel.setText(_translate("MainWindow", "Focal length:"))
        self.focalLengthValueLabel.setText(_translate("MainWindow", "0"))
        self.focalLengthUnitsLabel.setText(_translate("MainWindow", "mm"))
        self.focalLengthLabel_2.setText(_translate("MainWindow", "Focal Length "))
        self.transmittanceLabel.setText(_translate("MainWindow", "Transmittance"))
        self.focalLenthSliderUnitsLabel.setText(_translate("MainWindow", "mm"))
        self.transmittanceValueLabel.setText(_translate("MainWindow", "90"))
        self.transmittanceUnitsLabel.setText(_translate("MainWindow", "%"))
        self.focalLengthSliderValueLabel.setText(_translate("MainWindow", "8"))
        self.effectiveFocalLengthLabel.setText(_translate("MainWindow", "Effective focal length: "))
        self.effectiveFocalLengthValueLabel.setText(_translate("MainWindow", "0"))
        self.effectiveFocalLengthUnitsLabel.setText(_translate("MainWindow", "mm"))
        self.lensInfoButton.setText(_translate("MainWindow", "Info"))
        self.SensorBox.setTitle(_translate("MainWindow", "Camera"))
        self.cameraTypeLabel.setText(_translate("MainWindow", "Camera Type:"))
        self.cameraComboBox.setItemText(0, _translate("MainWindow", "Custom"))
        self.cameraLoadFileButton.setText(_translate("MainWindow", "Load Camera"))
        self.cameraLoadedFileLabel.setText(_translate("MainWindow", "No File Loaded"))
        self.resolutionyLabel.setText(_translate("MainWindow", "Resolution y:"))
        self.resolutionxLabel.setText(_translate("MainWindow", "Resolution x:"))
        self.pixelSizeLabel.setText(_translate("MainWindow", "Pixel Size:"))
        self.pixelSizeUnitsLabel.setText(_translate("MainWindow", "um"))
        self.pixelSizeValueLabel.setText(_translate("MainWindow", "0"))
        self.resolutionxValueLabel.setText(_translate("MainWindow", "0"))
        self.resolutionxUnitsLabel.setText(_translate("MainWindow", "px"))
        self.resolutionyValueLabel.setText(_translate("MainWindow", "0"))
        self.resolutionyUnitsLabel.setText(_translate("MainWindow", "px"))
        self.sensorNameLabel_2.setText(_translate("MainWindow", "Sensor"))
        self.sensorNameLabel.setText(_translate("MainWindow", "-"))
        self.cameraInfoButton.setText(_translate("MainWindow", "Info"))
        self.LightBox.setTitle(_translate("MainWindow", "Lights"))
        self.lightTypeLabel.setText(_translate("MainWindow", "Light Type:"))
        self.LightsComboBox.setItemText(0, _translate("MainWindow", "Custom"))
        self.LightsComboBox.setItemText(1, _translate("MainWindow", "Generic Led"))
        self.LightsComboBox.setItemText(2, _translate("MainWindow", "Generic Xenon"))
        self.LightsComboBox.setItemText(3, _translate("MainWindow", "Generic Tungsten"))
        self.LightsComboBox.setItemText(4, _translate("MainWindow", "Generic Halogen"))
        self.lightsLoadFileButton.setText(_translate("MainWindow", "Load Light"))
        self.lightsLoadedFileLabel.setText(_translate("MainWindow", "No File Loaded"))
        self.lightLedLabel.setText(_translate("MainWindow", "LED"))
        self.ledSpectrumLabel.setText(_translate("MainWindow", "Uses the spectral distribution of a generic white LED light."))
        self.luminousFluxLabel.setText(_translate("MainWindow", "L. flux"))
        self.beamAngleLabel.setText(_translate("MainWindow", "Beam Angle"))
        self.beamAngleValueLabel.setText(_translate("MainWindow", "15"))
        self.luminousFluxLineEdit.setText(_translate("MainWindow", "1000"))
        self.beamAngleUnitsLabel.setText(_translate("MainWindow", "deg"))
        self.liminousFluxUnitsLabel.setText(_translate("MainWindow", "lm"))
        self.lightXenonLabel.setText(_translate("MainWindow", "Xenon"))
        self.lightTungstenLabel.setText(_translate("MainWindow", "Tungsten"))
        self.lightHalogenLabel.setText(_translate("MainWindow", "Halogen"))
        self.lightsInfoButton.setText(_translate("MainWindow", "Info"))
        self.SceneBox.setTitle(_translate("MainWindow", "Scene / Operational Parameters"))
        self.dofLabel.setText(_translate("MainWindow", "Depth of Field"))
        self.overlapValueLabel.setText(_translate("MainWindow", "25"))
        self.speedLabel.setText(_translate("MainWindow", "Speed"))
        self.altitudeLabel.setText(_translate("MainWindow", "150"))
        self.overlapLabel.setText(_translate("MainWindow", "Overlap"))
        self.altitudeLabel_2.setText(_translate("MainWindow", "Altitude"))
        self.overlapUnitsLabel.setText(_translate("MainWindow", "%"))
        self.speedValueLabel.setText(_translate("MainWindow", "50"))
        self.speedUnitsLabel.setText(_translate("MainWindow", "cm/s"))
        self.altitudeUnitsLabel.setText(_translate("MainWindow", "cm"))
        self.dofValueLabel.setText(_translate("MainWindow", "100"))
        self.cameraOrientationLabel.setText(_translate("MainWindow", "Camera Orientation"))
        self.dofUnitsLabel.setText(_translate("MainWindow", "cm"))
        self.cameraOrientationCombobox.setItemText(0, _translate("MainWindow", "Portrait"))
        self.cameraOrientationCombobox.setItemText(1, _translate("MainWindow", "Landscape"))
        self.motionBlurValueLabel.setText(_translate("MainWindow", "2"))
        self.motionBlurLabel.setText(_translate("MainWindow", "Max Motion Blur"))
        self.motionBlurUnitsLabel.setText(_translate("MainWindow", "pixel"))
        self.bottomTypeLabel.setText(_translate("MainWindow", "Bottom Type"))
        self.bottomTypeCombo.setItemText(0, _translate("MainWindow", "Sand"))
        self.bottomTypeCombo.setItemText(1, _translate("MainWindow", "Custom"))
        self.bottomTypeCombo.setItemText(2, _translate("MainWindow", "Algae"))
        self.bottomTypeCombo.setItemText(3, _translate("MainWindow", "Coral"))
        self.bottomTypeCombo.setItemText(4, _translate("MainWindow", "Rock"))
        self.viewportCombobox.setItemText(0, _translate("MainWindow", "Flat"))
        self.viewportCombobox.setItemText(1, _translate("MainWindow", "Domed"))
        self.housingLabel.setText(_translate("MainWindow", "Housing Viewport Type"))
        self.saveButton.setText(_translate("MainWindow", "Save Configuration"))
        self.loadButton.setText(_translate("MainWindow", "Load Configuration"))
        self.exportButton.setText(_translate("MainWindow", "Export Report"))
        self.label.setText(_translate("MainWindow", "Sensors"))
        self.pushButton.setText(_translate("MainWindow", "+"))
        self.pushButton_2.setText(_translate("MainWindow", "-"))
        self.menuUnderwater_Optical_Systems_Calculator.setTitle(_translate("MainWindow", "Underwater Optical Systems Calculator"))
        self.menuFIle.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuMode.setTitle(_translate("MainWindow", "Mode"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionDesigner.setText(_translate("MainWindow", "Designer"))
        self.actionCompare_Sensors.setText(_translate("MainWindow", "Compare Sensors"))

