# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/UWOpticalSystemDesigner/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1202, 677)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LightBox = QtWidgets.QGroupBox(self.centralWidget)
        self.LightBox.setEnabled(True)
        self.LightBox.setFlat(False)
        self.LightBox.setCheckable(False)
        self.LightBox.setObjectName("LightBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LightBox)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.LightBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.LightsComboBox = QtWidgets.QComboBox(self.LightBox)
        self.LightsComboBox.setObjectName("LightsComboBox")
        self.LightsComboBox.addItem("")
        self.LightsComboBox.addItem("")
        self.LightsComboBox.addItem("")
        self.LightsComboBox.addItem("")
        self.LightsComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.LightsComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.lightStackedWidget = QtWidgets.QStackedWidget(self.LightBox)
        self.lightStackedWidget.setObjectName("lightStackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.page)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lightStackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lightsLoadFileButton = QtWidgets.QPushButton(self.page_2)
        self.lightsLoadFileButton.setObjectName("lightsLoadFileButton")
        self.verticalLayout_7.addWidget(self.lightsLoadFileButton)
        self.lightsLoadedFileLabel = QtWidgets.QLabel(self.page_2)
        self.lightsLoadedFileLabel.setObjectName("lightsLoadedFileLabel")
        self.verticalLayout_7.addWidget(self.lightsLoadedFileLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.lightStackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_27 = QtWidgets.QLabel(self.page_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_7.addWidget(self.label_27, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 1, 0, 1, 1)
        self.lightStackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_20 = QtWidgets.QLabel(self.page_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem3, 1, 0, 1, 1)
        self.lightStackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_28 = QtWidgets.QLabel(self.page_5)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem4, 1, 0, 1, 1)
        self.lightStackedWidget.addWidget(self.page_5)
        self.verticalLayout_2.addWidget(self.lightStackedWidget)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.luminousFluxLabel = QtWidgets.QLabel(self.LightBox)
        self.luminousFluxLabel.setObjectName("luminousFluxLabel")
        self.gridLayout_5.addWidget(self.luminousFluxLabel, 0, 0, 1, 1)
        self.beamAngleSlider = QtWidgets.QSlider(self.LightBox)
        self.beamAngleSlider.setMinimum(1)
        self.beamAngleSlider.setMaximum(90)
        self.beamAngleSlider.setProperty("value", 15)
        self.beamAngleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.beamAngleSlider.setObjectName("beamAngleSlider")
        self.gridLayout_5.addWidget(self.beamAngleSlider, 1, 1, 1, 1)
        self.beamAngleLabel = QtWidgets.QLabel(self.LightBox)
        self.beamAngleLabel.setObjectName("beamAngleLabel")
        self.gridLayout_5.addWidget(self.beamAngleLabel, 1, 0, 1, 1)
        self.beamAngleValueLabel = QtWidgets.QLabel(self.LightBox)
        self.beamAngleValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.beamAngleValueLabel.setObjectName("beamAngleValueLabel")
        self.gridLayout_5.addWidget(self.beamAngleValueLabel, 1, 2, 1, 1)
        self.luminousFluxLineEdit = QtWidgets.QLineEdit(self.LightBox)
        self.luminousFluxLineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.luminousFluxLineEdit.setMaxLength(10)
        self.luminousFluxLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.luminousFluxLineEdit.setObjectName("luminousFluxLineEdit")
        self.gridLayout_5.addWidget(self.luminousFluxLineEdit, 0, 1, 1, 1)
        self.beamAngleUnitsLabel = QtWidgets.QLabel(self.LightBox)
        self.beamAngleUnitsLabel.setObjectName("beamAngleUnitsLabel")
        self.gridLayout_5.addWidget(self.beamAngleUnitsLabel, 1, 3, 1, 1)
        self.liminousFluxUnitsLabel = QtWidgets.QLabel(self.LightBox)
        self.liminousFluxUnitsLabel.setObjectName("liminousFluxUnitsLabel")
        self.gridLayout_5.addWidget(self.liminousFluxUnitsLabel, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.horizontalLayout.addWidget(self.LightBox)
        self.verticalLineLeft = QtWidgets.QFrame(self.centralWidget)
        self.verticalLineLeft.setFrameShape(QtWidgets.QFrame.VLine)
        self.verticalLineLeft.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalLineLeft.setObjectName("verticalLineLeft")
        self.horizontalLayout.addWidget(self.verticalLineLeft)
        self.LensBox = QtWidgets.QGroupBox(self.centralWidget)
        self.LensBox.setObjectName("LensBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.LensBox)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LensComboBox = QtWidgets.QComboBox(self.LensBox)
        self.LensComboBox.setObjectName("LensComboBox")
        self.LensComboBox.addItem("")
        self.LensComboBox.addItem("")
        self.gridLayout_2.addWidget(self.LensComboBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.LensBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.lensStackedWidget = QtWidgets.QStackedWidget(self.LensBox)
        self.lensStackedWidget.setObjectName("lensStackedWidget")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lensLoadFileButton = QtWidgets.QPushButton(self.page_9)
        self.lensLoadFileButton.setObjectName("lensLoadFileButton")
        self.verticalLayout_8.addWidget(self.lensLoadFileButton)
        self.lensLoadedFileLabel = QtWidgets.QLabel(self.page_9)
        self.lensLoadedFileLabel.setObjectName("lensLoadedFileLabel")
        self.verticalLayout_8.addWidget(self.lensLoadedFileLabel)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.focalLengthLabel = QtWidgets.QLabel(self.page_9)
        self.focalLengthLabel.setObjectName("focalLengthLabel")
        self.horizontalLayout_6.addWidget(self.focalLengthLabel)
        self.focalLengthValueLabel = QtWidgets.QLabel(self.page_9)
        self.focalLengthValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.focalLengthValueLabel.setObjectName("focalLengthValueLabel")
        self.horizontalLayout_6.addWidget(self.focalLengthValueLabel)
        self.focalLengthUnitsLabel = QtWidgets.QLabel(self.page_9)
        self.focalLengthUnitsLabel.setObjectName("focalLengthUnitsLabel")
        self.horizontalLayout_6.addWidget(self.focalLengthUnitsLabel)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.lensStackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_10)
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_32 = QtWidgets.QLabel(self.page_10)
        self.label_32.setObjectName("label_32")
        self.gridLayout_10.addWidget(self.label_32, 0, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.page_10)
        self.label_34.setObjectName("label_34")
        self.gridLayout_10.addWidget(self.label_34, 2, 0, 1, 1)
        self.transmittanceSlider = QtWidgets.QSlider(self.page_10)
        self.transmittanceSlider.setMaximum(100)
        self.transmittanceSlider.setSliderPosition(90)
        self.transmittanceSlider.setTracking(True)
        self.transmittanceSlider.setOrientation(QtCore.Qt.Horizontal)
        self.transmittanceSlider.setObjectName("transmittanceSlider")
        self.gridLayout_10.addWidget(self.transmittanceSlider, 2, 1, 1, 1)
        self.focalLenthSliderUnitsLabel = QtWidgets.QLabel(self.page_10)
        self.focalLenthSliderUnitsLabel.setObjectName("focalLenthSliderUnitsLabel")
        self.gridLayout_10.addWidget(self.focalLenthSliderUnitsLabel, 0, 3, 1, 1)
        self.transmittanceValueLabel = QtWidgets.QLabel(self.page_10)
        self.transmittanceValueLabel.setMinimumSize(QtCore.QSize(30, 0))
        self.transmittanceValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.transmittanceValueLabel.setObjectName("transmittanceValueLabel")
        self.gridLayout_10.addWidget(self.transmittanceValueLabel, 2, 2, 1, 1)
        self.transmittanceUnitsLabel = QtWidgets.QLabel(self.page_10)
        self.transmittanceUnitsLabel.setObjectName("transmittanceUnitsLabel")
        self.gridLayout_10.addWidget(self.transmittanceUnitsLabel, 2, 3, 1, 1)
        self.focalLengthSliderValueLabel = QtWidgets.QLabel(self.page_10)
        self.focalLengthSliderValueLabel.setMinimumSize(QtCore.QSize(25, 0))
        self.focalLengthSliderValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.focalLengthSliderValueLabel.setObjectName("focalLengthSliderValueLabel")
        self.gridLayout_10.addWidget(self.focalLengthSliderValueLabel, 0, 2, 1, 1)
        self.focalLengthSlider = QtWidgets.QSlider(self.page_10)
        self.focalLengthSlider.setMaximum(200)
        self.focalLengthSlider.setProperty("value", 8)
        self.focalLengthSlider.setTracking(True)
        self.focalLengthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.focalLengthSlider.setObjectName("focalLengthSlider")
        self.gridLayout_10.addWidget(self.focalLengthSlider, 0, 1, 1, 1)
        self.lensStackedWidget.addWidget(self.page_10)
        self.verticalLayout_5.addWidget(self.lensStackedWidget)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.horizontalLayout.addWidget(self.LensBox)
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.SensorBox = QtWidgets.QGroupBox(self.centralWidget)
        self.SensorBox.setObjectName("SensorBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.SensorBox)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cameraTypeLabel = QtWidgets.QLabel(self.SensorBox)
        self.cameraTypeLabel.setObjectName("cameraTypeLabel")
        self.horizontalLayout_5.addWidget(self.cameraTypeLabel)
        self.cameraComboBox = QtWidgets.QComboBox(self.SensorBox)
        self.cameraComboBox.setObjectName("cameraComboBox")
        self.cameraComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.cameraComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.cameraStackedWidget = QtWidgets.QStackedWidget(self.SensorBox)
        self.cameraStackedWidget.setObjectName("cameraStackedWidget")
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_12)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.cameraLoadFileButton = QtWidgets.QPushButton(self.page_12)
        self.cameraLoadFileButton.setObjectName("cameraLoadFileButton")
        self.gridLayout_11.addWidget(self.cameraLoadFileButton, 0, 0, 1, 1)
        self.cameraLoadedFileLabel = QtWidgets.QLabel(self.page_12)
        self.cameraLoadedFileLabel.setObjectName("cameraLoadedFileLabel")
        self.gridLayout_11.addWidget(self.cameraLoadedFileLabel, 1, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.resolutionyLabel = QtWidgets.QLabel(self.page_12)
        self.resolutionyLabel.setObjectName("resolutionyLabel")
        self.gridLayout_9.addWidget(self.resolutionyLabel, 3, 0, 1, 1)
        self.resolutionxLabel = QtWidgets.QLabel(self.page_12)
        self.resolutionxLabel.setObjectName("resolutionxLabel")
        self.gridLayout_9.addWidget(self.resolutionxLabel, 2, 0, 1, 1)
        self.pixelSizeLabel = QtWidgets.QLabel(self.page_12)
        self.pixelSizeLabel.setObjectName("pixelSizeLabel")
        self.gridLayout_9.addWidget(self.pixelSizeLabel, 1, 0, 1, 1)
        self.pixelSizeUnitsLabel = QtWidgets.QLabel(self.page_12)
        self.pixelSizeUnitsLabel.setObjectName("pixelSizeUnitsLabel")
        self.gridLayout_9.addWidget(self.pixelSizeUnitsLabel, 1, 2, 1, 1)
        self.pixelSizeValueLabel = QtWidgets.QLabel(self.page_12)
        self.pixelSizeValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pixelSizeValueLabel.setObjectName("pixelSizeValueLabel")
        self.gridLayout_9.addWidget(self.pixelSizeValueLabel, 1, 1, 1, 1)
        self.resolutionxValueLabel = QtWidgets.QLabel(self.page_12)
        self.resolutionxValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resolutionxValueLabel.setObjectName("resolutionxValueLabel")
        self.gridLayout_9.addWidget(self.resolutionxValueLabel, 2, 1, 1, 1)
        self.resolutionxUnitsLabel = QtWidgets.QLabel(self.page_12)
        self.resolutionxUnitsLabel.setObjectName("resolutionxUnitsLabel")
        self.gridLayout_9.addWidget(self.resolutionxUnitsLabel, 2, 2, 1, 1)
        self.resolutionyValueLabel = QtWidgets.QLabel(self.page_12)
        self.resolutionyValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resolutionyValueLabel.setObjectName("resolutionyValueLabel")
        self.gridLayout_9.addWidget(self.resolutionyValueLabel, 3, 1, 1, 1)
        self.resolutionyUnitsLabel = QtWidgets.QLabel(self.page_12)
        self.resolutionyUnitsLabel.setObjectName("resolutionyUnitsLabel")
        self.gridLayout_9.addWidget(self.resolutionyUnitsLabel, 3, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.page_12)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 0, 0, 1, 1)
        self.sensorNameLabel = QtWidgets.QLabel(self.page_12)
        self.sensorNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sensorNameLabel.setObjectName("sensorNameLabel")
        self.gridLayout_9.addWidget(self.sensorNameLabel, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_9, 2, 0, 1, 1)
        self.cameraStackedWidget.addWidget(self.page_12)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.cameraStackedWidget.addWidget(self.page_13)
        self.verticalLayout_6.addWidget(self.cameraStackedWidget)
        spacerItem7 = QtWidgets.QSpacerItem(287, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout.addWidget(self.SensorBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.SceneBox = QtWidgets.QGroupBox(self.centralWidget)
        self.SceneBox.setObjectName("SceneBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.SceneBox)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.overlapValueLabel = QtWidgets.QLabel(self.SceneBox)
        self.overlapValueLabel.setMinimumSize(QtCore.QSize(25, 0))
        self.overlapValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.overlapValueLabel.setObjectName("overlapValueLabel")
        self.gridLayout_3.addWidget(self.overlapValueLabel, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.SceneBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.altitudeLabel = QtWidgets.QLabel(self.SceneBox)
        self.altitudeLabel.setMinimumSize(QtCore.QSize(25, 0))
        self.altitudeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.altitudeLabel.setObjectName("altitudeLabel")
        self.gridLayout_3.addWidget(self.altitudeLabel, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.SceneBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.SceneBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.SceneBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.SceneBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.overlapSlider = QtWidgets.QSlider(self.SceneBox)
        self.overlapSlider.setOrientation(QtCore.Qt.Horizontal)
        self.overlapSlider.setObjectName("overlapSlider")
        self.gridLayout_3.addWidget(self.overlapSlider, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.SceneBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 3, 1, 1)
        self.speedValueLabel = QtWidgets.QLabel(self.SceneBox)
        self.speedValueLabel.setMinimumSize(QtCore.QSize(25, 0))
        self.speedValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speedValueLabel.setObjectName("speedValueLabel")
        self.gridLayout_3.addWidget(self.speedValueLabel, 2, 2, 1, 1)
        self.speedUnitsLabel = QtWidgets.QLabel(self.SceneBox)
        self.speedUnitsLabel.setObjectName("speedUnitsLabel")
        self.gridLayout_3.addWidget(self.speedUnitsLabel, 2, 3, 1, 1)
        self.speedSlider = QtWidgets.QSlider(self.SceneBox)
        self.speedSlider.setMaximum(400)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName("speedSlider")
        self.gridLayout_3.addWidget(self.speedSlider, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 0, 4, 1, 1)
        self.altitudeUnitsLabel = QtWidgets.QLabel(self.SceneBox)
        self.altitudeUnitsLabel.setObjectName("altitudeUnitsLabel")
        self.gridLayout_3.addWidget(self.altitudeUnitsLabel, 0, 3, 1, 1)
        self.bottomTypeCombo = QtWidgets.QComboBox(self.SceneBox)
        self.bottomTypeCombo.setObjectName("bottomTypeCombo")
        self.bottomTypeCombo.addItem("")
        self.bottomTypeCombo.addItem("")
        self.bottomTypeCombo.addItem("")
        self.bottomTypeCombo.addItem("")
        self.bottomTypeCombo.addItem("")
        self.gridLayout_3.addWidget(self.bottomTypeCombo, 2, 7, 1, 1)
        self.altitudeSlider = QtWidgets.QSlider(self.SceneBox)
        self.altitudeSlider.setMaximum(1500)
        self.altitudeSlider.setSingleStep(0)
        self.altitudeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.altitudeSlider.setObjectName("altitudeSlider")
        self.gridLayout_3.addWidget(self.altitudeSlider, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.SceneBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 5, 1, 1)
        self.dofUnitsLabel = QtWidgets.QLabel(self.SceneBox)
        self.dofUnitsLabel.setObjectName("dofUnitsLabel")
        self.gridLayout_3.addWidget(self.dofUnitsLabel, 1, 9, 1, 1)
        self.dofValueLabel = QtWidgets.QLabel(self.SceneBox)
        self.dofValueLabel.setMinimumSize(QtCore.QSize(25, 0))
        self.dofValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dofValueLabel.setObjectName("dofValueLabel")
        self.gridLayout_3.addWidget(self.dofValueLabel, 1, 8, 1, 1)
        self.motionBlurUnitsLabel = QtWidgets.QLabel(self.SceneBox)
        self.motionBlurUnitsLabel.setObjectName("motionBlurUnitsLabel")
        self.gridLayout_3.addWidget(self.motionBlurUnitsLabel, 0, 9, 1, 1)
        self.motionBlurValueLabel = QtWidgets.QLabel(self.SceneBox)
        self.motionBlurValueLabel.setMinimumSize(QtCore.QSize(25, 0))
        self.motionBlurValueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.motionBlurValueLabel.setObjectName("motionBlurValueLabel")
        self.gridLayout_3.addWidget(self.motionBlurValueLabel, 0, 8, 1, 1)
        self.motionBlurSlider = QtWidgets.QSlider(self.SceneBox)
        self.motionBlurSlider.setOrientation(QtCore.Qt.Horizontal)
        self.motionBlurSlider.setObjectName("motionBlurSlider")
        self.gridLayout_3.addWidget(self.motionBlurSlider, 0, 7, 1, 1)
        self.dofSlider = QtWidgets.QSlider(self.SceneBox)
        self.dofSlider.setMaximum(600)
        self.dofSlider.setOrientation(QtCore.Qt.Horizontal)
        self.dofSlider.setObjectName("dofSlider")
        self.gridLayout_3.addWidget(self.dofSlider, 1, 7, 1, 1)
        self.verticalLayout.addWidget(self.SceneBox)
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.OutputBox = QtWidgets.QGroupBox(self.centralWidget)
        self.OutputBox.setObjectName("OutputBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.OutputBox)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem9 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem9, 4, 0, 1, 1)
        self.FOVyLabel = QtWidgets.QLabel(self.OutputBox)
        self.FOVyLabel.setObjectName("FOVyLabel")
        self.gridLayout_4.addWidget(self.FOVyLabel, 1, 0, 1, 1)
        self.FOVxLabel = QtWidgets.QLabel(self.OutputBox)
        self.FOVxLabel.setObjectName("FOVxLabel")
        self.gridLayout_4.addWidget(self.FOVxLabel, 0, 0, 1, 1)
        self.apertureLabel = QtWidgets.QLabel(self.OutputBox)
        self.apertureLabel.setObjectName("apertureLabel")
        self.gridLayout_4.addWidget(self.apertureLabel, 2, 0, 1, 1)
        self.exposureLabel = QtWidgets.QLabel(self.OutputBox)
        self.exposureLabel.setObjectName("exposureLabel")
        self.gridLayout_4.addWidget(self.exposureLabel, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.OutputBox)
        self.line_5 = QtWidgets.QFrame(self.centralWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.saveButton = QtWidgets.QPushButton(self.centralWidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_7.addWidget(self.saveButton)
        self.loadButton = QtWidgets.QPushButton(self.centralWidget)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_7.addWidget(self.loadButton)
        self.exportButton = QtWidgets.QPushButton(self.centralWidget)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout_7.addWidget(self.exportButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1202, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuUnderwater_Optical_Systems_Calculator = QtWidgets.QMenu(self.menuBar)
        self.menuUnderwater_Optical_Systems_Calculator.setObjectName("menuUnderwater_Optical_Systems_Calculator")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuUnderwater_Optical_Systems_Calculator.menuAction())

        self.retranslateUi(MainWindow)
        self.lightStackedWidget.setCurrentIndex(0)
        self.lensStackedWidget.setCurrentIndex(0)
        self.cameraStackedWidget.setCurrentIndex(0)
        self.LightsComboBox.currentIndexChanged['int'].connect(self.lightStackedWidget.setCurrentIndex)
        self.LensComboBox.currentIndexChanged['int'].connect(self.lensStackedWidget.setCurrentIndex)
        self.beamAngleSlider.valueChanged['int'].connect(self.beamAngleValueLabel.setNum)
        self.altitudeSlider.valueChanged['int'].connect(self.altitudeLabel.setNum)
        self.overlapSlider.valueChanged['int'].connect(self.overlapValueLabel.setNum)
        self.motionBlurSlider.valueChanged['int'].connect(self.motionBlurValueLabel.setNum)
        self.speedSlider.valueChanged['int'].connect(self.speedValueLabel.setNum)
        self.dofSlider.valueChanged['int'].connect(self.dofValueLabel.setNum)
        self.transmittanceSlider.valueChanged['int'].connect(self.transmittanceValueLabel.setNum)
        self.focalLengthSlider.valueChanged['int'].connect(self.focalLengthSliderValueLabel.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Underwater Optical Systems Calculator"))
        self.LightBox.setTitle(_translate("MainWindow", "Lights"))
        self.label.setText(_translate("MainWindow", "Light Type:"))
        self.LightsComboBox.setItemText(0, _translate("MainWindow", "Generic Led"))
        self.LightsComboBox.setItemText(1, _translate("MainWindow", "Custom"))
        self.LightsComboBox.setItemText(2, _translate("MainWindow", "Generic Xenon"))
        self.LightsComboBox.setItemText(3, _translate("MainWindow", "Generic Tungsten"))
        self.LightsComboBox.setItemText(4, _translate("MainWindow", "Generic Halogen"))
        self.label_21.setText(_translate("MainWindow", "LED"))
        self.label_3.setText(_translate("MainWindow", "Uses the spectral distribution of a generic white LED light."))
        self.lightsLoadFileButton.setText(_translate("MainWindow", "Load Light"))
        self.lightsLoadedFileLabel.setText(_translate("MainWindow", "No File Loaded"))
        self.label_27.setText(_translate("MainWindow", "Xenon"))
        self.label_20.setText(_translate("MainWindow", "Tungsten"))
        self.label_28.setText(_translate("MainWindow", "Halogen"))
        self.luminousFluxLabel.setText(_translate("MainWindow", "Luminous flux"))
        self.beamAngleLabel.setText(_translate("MainWindow", "Beam Angle"))
        self.beamAngleValueLabel.setText(_translate("MainWindow", "15"))
        self.luminousFluxLineEdit.setText(_translate("MainWindow", "1000"))
        self.beamAngleUnitsLabel.setText(_translate("MainWindow", "deg"))
        self.liminousFluxUnitsLabel.setText(_translate("MainWindow", "lumen"))
        self.LensBox.setTitle(_translate("MainWindow", "Lens"))
        self.LensComboBox.setItemText(0, _translate("MainWindow", "Custom "))
        self.LensComboBox.setItemText(1, _translate("MainWindow", "Generic"))
        self.label_2.setText(_translate("MainWindow", "Lens Type:"))
        self.lensLoadFileButton.setText(_translate("MainWindow", "Load Lens"))
        self.lensLoadedFileLabel.setText(_translate("MainWindow", "No File Loaded"))
        self.focalLengthLabel.setText(_translate("MainWindow", "Focal length:"))
        self.focalLengthValueLabel.setText(_translate("MainWindow", "0"))
        self.focalLengthUnitsLabel.setText(_translate("MainWindow", "mm"))
        self.label_32.setText(_translate("MainWindow", "Focal Length "))
        self.label_34.setText(_translate("MainWindow", "Transmittance"))
        self.focalLenthSliderUnitsLabel.setText(_translate("MainWindow", "mm"))
        self.transmittanceValueLabel.setText(_translate("MainWindow", "90"))
        self.transmittanceUnitsLabel.setText(_translate("MainWindow", "%"))
        self.focalLengthSliderValueLabel.setText(_translate("MainWindow", "8"))
        self.SensorBox.setTitle(_translate("MainWindow", "Camera"))
        self.cameraTypeLabel.setText(_translate("MainWindow", "Camera Type:"))
        self.cameraComboBox.setItemText(0, _translate("MainWindow", "Custom"))
        self.cameraLoadFileButton.setText(_translate("MainWindow", "Load Camera"))
        self.cameraLoadedFileLabel.setText(_translate("MainWindow", "No File Loaded"))
        self.resolutionyLabel.setText(_translate("MainWindow", "Resolution y:"))
        self.resolutionxLabel.setText(_translate("MainWindow", "Resolution x:"))
        self.pixelSizeLabel.setText(_translate("MainWindow", "Pixel Size:"))
        self.pixelSizeUnitsLabel.setText(_translate("MainWindow", "um"))
        self.pixelSizeValueLabel.setText(_translate("MainWindow", "0"))
        self.resolutionxValueLabel.setText(_translate("MainWindow", "0"))
        self.resolutionxUnitsLabel.setText(_translate("MainWindow", "px"))
        self.resolutionyValueLabel.setText(_translate("MainWindow", "0"))
        self.resolutionyUnitsLabel.setText(_translate("MainWindow", "px"))
        self.label_11.setText(_translate("MainWindow", "Sensor"))
        self.sensorNameLabel.setText(_translate("MainWindow", "-"))
        self.SceneBox.setTitle(_translate("MainWindow", "Scene / Operational Parameters"))
        self.overlapValueLabel.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Speed"))
        self.altitudeLabel.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Overlap"))
        self.label_6.setText(_translate("MainWindow", "Depth of Field"))
        self.label_5.setText(_translate("MainWindow", "Bottom Type"))
        self.label_4.setText(_translate("MainWindow", "Altitude"))
        self.label_15.setText(_translate("MainWindow", "%"))
        self.speedValueLabel.setText(_translate("MainWindow", "1"))
        self.speedUnitsLabel.setText(_translate("MainWindow", "cm/s"))
        self.altitudeUnitsLabel.setText(_translate("MainWindow", "cm"))
        self.bottomTypeCombo.setItemText(0, _translate("MainWindow", "Sand"))
        self.bottomTypeCombo.setItemText(1, _translate("MainWindow", "Custom"))
        self.bottomTypeCombo.setItemText(2, _translate("MainWindow", "Algae"))
        self.bottomTypeCombo.setItemText(3, _translate("MainWindow", "Coral"))
        self.bottomTypeCombo.setItemText(4, _translate("MainWindow", "Rock"))
        self.label_17.setText(_translate("MainWindow", "Max Motion Blur"))
        self.dofUnitsLabel.setText(_translate("MainWindow", "cm"))
        self.dofValueLabel.setText(_translate("MainWindow", "1"))
        self.motionBlurUnitsLabel.setText(_translate("MainWindow", "pixel"))
        self.motionBlurValueLabel.setText(_translate("MainWindow", "2"))
        self.OutputBox.setTitle(_translate("MainWindow", "Output"))
        self.FOVyLabel.setText(_translate("MainWindow", "FOV_y"))
        self.FOVxLabel.setText(_translate("MainWindow", "FOV_x"))
        self.apertureLabel.setText(_translate("MainWindow", "Aperture"))
        self.exposureLabel.setText(_translate("MainWindow", "Exposure"))
        self.saveButton.setText(_translate("MainWindow", "Save Configuration"))
        self.loadButton.setText(_translate("MainWindow", "Load Configuration"))
        self.exportButton.setText(_translate("MainWindow", "Export Report"))
        self.menuUnderwater_Optical_Systems_Calculator.setTitle(_translate("MainWindow", "Underwater Optical Systems Calculator"))

