# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/UWOpticalSystemDesigner/mainwindow.ui'
#
# Created: Wed Jun 13 18:45:26 2018
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1202, 675)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LightBox = QtWidgets.QGroupBox(self.centralWidget)
        self.LightBox.setEnabled(True)
        self.LightBox.setFlat(False)
        self.LightBox.setCheckable(False)
        self.LightBox.setObjectName("LightBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LightBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.LightBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.LightsComboBox = QtWidgets.QComboBox(self.LightBox)
        self.LightsComboBox.setObjectName("LightsComboBox")
        self.LightsComboBox.addItem("")
        self.LightsComboBox.addItem("")
        self.LightsComboBox.addItem("")
        self.LightsComboBox.addItem("")
        self.LightsComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.LightsComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.lightStackedWidget = QtWidgets.QStackedWidget(self.LightBox)
        self.lightStackedWidget.setObjectName("lightStackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.label_18 = QtWidgets.QLabel(self.page)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.page)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.lightStackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_19 = QtWidgets.QLabel(self.page_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 0, 1, 1, 1)
        self.lightStackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_27 = QtWidgets.QLabel(self.page_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_7.addWidget(self.label_27, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem3, 1, 0, 1, 1)
        self.lightStackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_20 = QtWidgets.QLabel(self.page_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem4, 1, 0, 1, 1)
        self.lightStackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_28 = QtWidgets.QLabel(self.page_5)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 1, 0, 1, 1)
        self.lightStackedWidget.addWidget(self.page_5)
        self.verticalLayout_2.addWidget(self.lightStackedWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_22 = QtWidgets.QLabel(self.LightBox)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.LightBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.label_23 = QtWidgets.QLabel(self.LightBox)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_3.addWidget(self.label_23)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_24 = QtWidgets.QLabel(self.LightBox)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.LightBox)
        self.horizontalSlider_2.setMinimum(1)
        self.horizontalSlider_2.setMaximum(90)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_4.addWidget(self.horizontalSlider_2)
        self.label_26 = QtWidgets.QLabel(self.LightBox)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_4.addWidget(self.label_26)
        self.label_25 = QtWidgets.QLabel(self.LightBox)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_4.addWidget(self.label_25)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addWidget(self.LightBox)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.LensBox = QtWidgets.QGroupBox(self.centralWidget)
        self.LensBox.setObjectName("LensBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.LensBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.LensBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.LensBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.LensBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.LensBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 4, 0, 1, 1)
        self.horizontalLayout.addWidget(self.LensBox)
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.SensorBox = QtWidgets.QGroupBox(self.centralWidget)
        self.SensorBox.setObjectName("SensorBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SensorBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem10 = QtWidgets.QSpacerItem(439, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem10)
        self.horizontalLayout.addWidget(self.SensorBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.SceneBox = QtWidgets.QGroupBox(self.centralWidget)
        self.SceneBox.setObjectName("SceneBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.SceneBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.SceneBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 1, 8, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 1, 9, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.SceneBox)
        self.label_11.setMinimumSize(QtCore.QSize(25, 0))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.SceneBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.altitudeLabel = QtWidgets.QLabel(self.SceneBox)
        self.altitudeLabel.setMinimumSize(QtCore.QSize(25, 0))
        self.altitudeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.altitudeLabel.setObjectName("altitudeLabel")
        self.gridLayout_3.addWidget(self.altitudeLabel, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.SceneBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.SceneBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.SceneBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.SceneBox)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.SceneBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 6, 1, 1)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.SceneBox)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.gridLayout_3.addWidget(self.horizontalSlider_3, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.SceneBox)
        self.label_13.setMinimumSize(QtCore.QSize(25, 0))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 2, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.SceneBox)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_3.addWidget(self.horizontalSlider, 2, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 0, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.SceneBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.SceneBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.SceneBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 3, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.SceneBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_2, 2, 8, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.SceneBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 6, 1, 1)
        self.altitudeSlider = QtWidgets.QSlider(self.SceneBox)
        self.altitudeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.altitudeSlider.setObjectName("altitudeSlider")
        self.gridLayout_3.addWidget(self.altitudeSlider, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.SceneBox)
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.OutputBox = QtWidgets.QGroupBox(self.centralWidget)
        self.OutputBox.setObjectName("OutputBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.OutputBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem13 = QtWidgets.QSpacerItem(20, 125, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem13, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.OutputBox)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1202, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuUnderwater_Optical_Systems_Calculator = QtWidgets.QMenu(self.menuBar)
        self.menuUnderwater_Optical_Systems_Calculator.setObjectName("menuUnderwater_Optical_Systems_Calculator")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuUnderwater_Optical_Systems_Calculator.menuAction())

        self.retranslateUi(MainWindow)
        self.lightStackedWidget.setCurrentIndex(0)
        self.LightsComboBox.currentIndexChanged['int'].connect(self.lightStackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LightBox.setTitle(_translate("MainWindow", "Lights"))
        self.label.setText(_translate("MainWindow", "Light Type:"))
        self.LightsComboBox.setItemText(0, _translate("MainWindow", "Led"))
        self.LightsComboBox.setItemText(1, _translate("MainWindow", "Custom"))
        self.LightsComboBox.setItemText(2, _translate("MainWindow", "Xenon"))
        self.LightsComboBox.setItemText(3, _translate("MainWindow", "Tungsten"))
        self.LightsComboBox.setItemText(4, _translate("MainWindow", "Halogen"))
        self.label_18.setText(_translate("MainWindow", "Led Temperature"))
        self.label_21.setText(_translate("MainWindow", "LED"))
        self.label_19.setText(_translate("MainWindow", "Load Custom Light Profile"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label_27.setText(_translate("MainWindow", "Xenon"))
        self.label_20.setText(_translate("MainWindow", "Tungsten"))
        self.label_28.setText(_translate("MainWindow", "Halogen"))
        self.label_22.setText(_translate("MainWindow", "Luminous flux"))
        self.label_23.setText(_translate("MainWindow", "lumen"))
        self.label_24.setText(_translate("MainWindow", "Beam Angle"))
        self.label_26.setText(_translate("MainWindow", "15"))
        self.label_25.setText(_translate("MainWindow", "deg"))
        self.LensBox.setTitle(_translate("MainWindow", "Lens"))
        self.label_9.setText(_translate("MainWindow", "Focal length"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "mm"))
        self.label_2.setText(_translate("MainWindow", "Lens Type:"))
        self.SensorBox.setTitle(_translate("MainWindow", "Sensor"))
        self.SceneBox.setTitle(_translate("MainWindow", "Scene"))
        self.label_11.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Speed"))
        self.altitudeLabel.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Overlap"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "Altitude"))
        self.label_5.setText(_translate("MainWindow", "Bottom Type"))
        self.label_13.setText(_translate("MainWindow", "1"))
        self.label_15.setText(_translate("MainWindow", "%"))
        self.label_14.setText(_translate("MainWindow", "m/s"))
        self.label_10.setText(_translate("MainWindow", "m"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Sand"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Custom"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Algae"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Coral"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Rock"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.OutputBox.setTitle(_translate("MainWindow", "Output"))
        self.menuUnderwater_Optical_Systems_Calculator.setTitle(_translate("MainWindow", "Underwater Optical Systems Calculator"))

